import{currentAccessToken,edgeUrl,getSupabaseClient}from'./supabase-client.js';
import{getAdminState}from'./auth.js?v=53';
import{openHiveAdmin}from'./hive-admin.js?v=52';
const client=getSupabaseClient();
let adminState=getAdminState();
let editingProductId=null;

async function adminEdge(action,payload={}){const token=await currentAccessToken();if(!token)throw new Error('Please sign in again.');const response=await fetch(edgeUrl('veterans-admin'),{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({action,...payload})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Admin request failed.');return data;}
function escapeHtml(value){return String(value).replace(/[&<>'\"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[ch]));}
function money(minor){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(minor||0)/100);}
function tabButton(key,label,active=false){return`<button type="button" data-admin-tab="${key}"${active?' class="active"':''}>${label}</button>`;}

function renderShell(){const host=document.getElementById('admin-tools');if(!host||!adminState.approved||adminState.passwordChangeRequired)return;host.innerHTML=`<div class="admin-tabs">${tabButton('home','Admin Home',true)}${tabButton('products','Products')}${tabButton('orders','Orders')}${tabButton('hives','Hive Stories')}${tabButton('chat','Community')}${adminState.role==='owner'?tabButton('access','Approved Emails'):''}</div><div id="admin-panel"></div>`;host.querySelectorAll('[data-admin-tab]').forEach(btn=>btn.addEventListener('click',()=>openTab(btn.dataset.adminTab,btn)));openTab('home',host.querySelector('[data-admin-tab="home"]'));}

function renderAdminHome(panel){panel.innerHTML=`<div class="admin-card admin-home-card"><h3>Site Management</h3><p>Choose what you want to manage.</p><div class="admin-home-grid"><button type="button" data-open-admin-tab="products"><strong>Products</strong><span>Add products, upload photos, set prices and stock.</span></button><button type="button" data-open-admin-tab="orders"><strong>Orders</strong><span>Review orders and update fulfillment status.</span></button><button type="button" data-open-admin-tab="hives"><strong>Hive Stories</strong><span>Add, edit, publish, or remove stories from hives you have helped.</span></button><button type="button" data-open-admin-tab="chat"><strong>Community</strong><span>Moderate chat messages, photos, and blocked guests.</span></button>${adminState.role==='owner'?'<button type="button" data-open-admin-tab="access"><strong>Approved Emails</strong><span>Add or deactivate admin emails.</span></button>':''}</div></div>`;panel.querySelectorAll('[data-open-admin-tab]').forEach(btn=>btn.addEventListener('click',()=>{const tab=document.querySelector(`[data-admin-tab="${btn.dataset.openAdminTab}"]`);if(tab)tab.click();}));}

async function openTab(tab,button){document.querySelectorAll('[data-admin-tab]').forEach(b=>b.classList.toggle('active',b===button));const panel=document.getElementById('admin-panel');if(!panel)return;panel.innerHTML='<p class="admin-loading">Loading…</p>';try{if(tab==='home')renderAdminHome(panel);if(tab==='products')await renderProducts(panel);if(tab==='orders')await renderOrders(panel);if(tab==='chat')await renderChatModeration(panel);if(tab==='access'&&adminState.role==='owner')await renderAdminAccess(panel);if(tab==='hives'){panel.innerHTML='<div id="hive-admin-tools"></div>';await openHiveAdmin();}}catch(error){panel.innerHTML=`<div class="status-error">${escapeHtml(error.message)}</div>`;}}

function productRow(p){return`<div class="admin-list-row"><div><strong>${escapeHtml(p.name)}</strong><span>${money(p.price_minor_units)} · ${p.stock_quantity} in stock · ${p.active?'Active':'Hidden'}</span></div><div class="row-actions"><button type="button" data-edit-product="${p.id}">Edit</button><button type="button" data-delete-product="${p.id}">Delete</button></div></div>`;}
async function renderProducts(panel){const{data,error}=await client.from('veterans_products').select('*').order('created_at',{ascending:false});if(error)throw error;panel.innerHTML=`<div class="admin-grid-two"><form id="product-form" class="admin-card"><h3>${editingProductId?'Edit Product':'Add Product'}</h3><label>Name<input name="name" maxlength="120" required></label><label>Description<textarea name="description" rows="4"></textarea></label><div class="form-row"><label>Price ($)<input name="price" type="number" min="0" step="0.01" required></label><label>Stock<input name="stock" type="number" min="0" step="1" required></label></div><label>Product Photo<input name="photo" type="file" accept="image/jpeg,image/png,image/webp"></label><label class="check-row"><input name="active" type="checkbox" checked> Active in store</label><div class="form-actions"><button class="gold-cta compact" type="submit">Save Product</button><button class="outline-button" type="button" data-reset-product>Clear</button></div><p class="admin-form-status" id="product-status"></p></form><div class="admin-card"><h3>Products</h3><div class="admin-list">${(data||[]).map(productRow).join('')||'<p>No products yet.</p>'}</div></div></div>`;const form=panel.querySelector('#product-form');form.addEventListener('submit',saveProduct);panel.querySelector('[data-reset-product]').addEventListener('click',()=>{editingProductId=null;renderProducts(panel);});panel.querySelectorAll('[data-edit-product]').forEach(btn=>btn.addEventListener('click',()=>fillProductForm(form,(data||[]).find(p=>p.id===btn.dataset.editProduct))));panel.querySelectorAll('[data-delete-product]').forEach(btn=>btn.addEventListener('click',()=>deleteProduct(btn.dataset.deleteProduct,panel)));}
function fillProductForm(form,p){if(!p)return;editingProductId=p.id;form.name.value=p.name;form.description.value=p.description||'';form.price.value=(p.price_minor_units/100).toFixed(2);form.stock.value=p.stock_quantity;form.active.checked=p.active;form.scrollIntoView({behavior:'smooth',block:'center'});}
async function uploadProductPhoto(file,productId){if(!file)return null;if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Product photo must be JPG, PNG, or WebP.');if(file.size>5*1024*1024)throw new Error('Product photo must be 5 MB or smaller.');const ext=file.type==='image/png'?'png':file.type==='image/webp'?'webp':'jpg';const path=`${productId}/${crypto.randomUUID()}.${ext}`;const{error}=await client.storage.from('veterans-product-images').upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;return path;}
async function saveProduct(event){event.preventDefault();const form=event.currentTarget,status=form.querySelector('#product-status');status.textContent='Saving…';try{const productId=editingProductId||crypto.randomUUID();let imagePath;if(form.photo.files[0])imagePath=await uploadProductPhoto(form.photo.files[0],productId);const payload={id:productId,name:form.name.value.trim(),description:form.description.value.trim(),price_minor_units:Math.round(Number(form.price.value)*100),stock_quantity:Number(form.stock.value),currency:'USD',active:form.active.checked};if(imagePath)payload.image_path=imagePath;const query=editingProductId?client.from('veterans_products').update(payload).eq('id',productId):client.from('veterans_products').insert(payload);const{error}=await query;if(error)throw error;editingProductId=null;await renderProducts(document.getElementById('admin-panel'));window.dispatchEvent(new CustomEvent('veterans-products-updated'));}catch(error){status.textContent=error.message;}}
async function deleteProduct(id,panel){if(!confirm('Delete this product from the store?'))return;const{error}=await client.from('veterans_products').delete().eq('id',id);if(error)throw error;await renderProducts(panel);window.dispatchEvent(new CustomEvent('veterans-products-updated'));}

async function renderOrders(panel){const{data,error}=await client.from('veterans_orders').select('*,veterans_order_items(*)').order('created_at',{ascending:false}).limit(100);if(error)throw error;panel.innerHTML=`<div class="admin-card"><h3>Orders</h3><div class="admin-list">${(data||[]).map(orderRow).join('')||'<p>No orders yet.</p>'}</div></div>`;panel.querySelectorAll('[data-order-status]').forEach(select=>select.addEventListener('change',async()=>{const{error:updateError}=await client.from('veterans_orders').update({fulfillment_status:select.value}).eq('id',select.dataset.orderStatus);if(updateError){alert(updateError.message);await renderOrders(panel);}}));}
function orderRow(order){const items=order.veterans_order_items||[];return`<div class="order-card"><div class="order-head"><div><strong>${escapeHtml(order.paypal_order_id)}</strong><span>${new Date(order.created_at).toLocaleString()}</span></div><strong>${money(order.total_minor_units)}</strong></div><p>${escapeHtml(order.customer_email||'Customer email provided through PayPal')}</p><ul>${items.map(i=>`<li>${escapeHtml(i.product_name_snapshot)} × ${i.quantity}</li>`).join('')}</ul><div class="form-row"><span>Payment: ${escapeHtml(order.payment_status)}</span><label>Fulfillment<select data-order-status="${order.id}">${['New','Processing','Shipped','Completed','Cancelled'].map(s=>`<option ${s===order.fulfillment_status?'selected':''}>${s}</option>`).join('')}</select></label></div></div>`;}

async function renderChatModeration(panel){const[{data:msgs,error},{data:blocks,error:blockError}]=await Promise.all([client.from('veterans_chat_messages').select('*').order('created_at',{ascending:false}).limit(100),client.from('veterans_chat_blocks').select('*').eq('active',true).order('created_at',{ascending:false})]);if(error)throw error;if(blockError)throw blockError;panel.innerHTML=`<div class="admin-grid-two"><div class="admin-card"><h3>Recent Community Chat</h3><div class="admin-list">${(msgs||[]).map(chatAdminRow).join('')||'<p>No messages yet.</p>'}</div></div><div class="admin-card"><h3>Blocked Guests</h3><div class="admin-list">${(blocks||[]).map(blockRow).join('')||'<p>No blocked guests.</p>'}</div></div></div>`;panel.querySelectorAll('[data-delete-message]').forEach(btn=>btn.addEventListener('click',async()=>{await adminEdge('chat.delete',{messageId:btn.dataset.deleteMessage});await renderChatModeration(panel);}));panel.querySelectorAll('[data-remove-photo]').forEach(btn=>btn.addEventListener('click',async()=>{await adminEdge('chat.remove_photo',{messageId:btn.dataset.removePhoto});await renderChatModeration(panel);}));panel.querySelectorAll('[data-block-guest]').forEach(btn=>btn.addEventListener('click',async()=>{const reason=prompt('Reason for blocking this guest?')||'';await adminEdge('chat.block',{guestId:btn.dataset.blockGuest,reason});await renderChatModeration(panel);}));panel.querySelectorAll('[data-unblock-guest]').forEach(btn=>btn.addEventListener('click',async()=>{await adminEdge('chat.unblock',{guestId:btn.dataset.unblockGuest});await renderChatModeration(panel);}));}
function chatAdminRow(m){return`<div class="admin-list-row stacked"><div><strong>${escapeHtml(m.display_name)}</strong><span>${new Date(m.created_at).toLocaleString()} · guest ${escapeHtml(m.guest_id)}</span><p>${escapeHtml(m.body||(m.deleted_at?'[deleted]':'[photo only]'))}</p></div><div class="row-actions">${m.image_path&&!m.deleted_at?`<button data-remove-photo="${m.id}">Remove Photo</button>`:''}${!m.deleted_at?`<button data-delete-message="${m.id}">Delete</button>`:''}<button data-block-guest="${m.guest_id}">Block Guest</button></div></div>`;}
function blockRow(b){return`<div class="admin-list-row"><div><strong>${escapeHtml(b.guest_id)}</strong><span>${escapeHtml(b.reason||'No reason')}</span></div><button data-unblock-guest="${b.guest_id}">Unblock</button></div>`;}

async function renderAdminAccess(panel){const result=await adminEdge('admins.list');panel.innerHTML=`<div class="admin-grid-two"><form id="approve-admin-form" class="admin-card"><h3>Add Approved Admin Email</h3><p>Owners can add approved management emails. Existing owner emails stay owners.</p><label>Email<input name="email" type="email" required placeholder="name@gmail.com"></label><button class="gold-cta compact" type="submit">Approve Email</button><p id="admin-access-status"></p></form><div class="admin-card"><h3>Approved Owners & Admins</h3><div class="admin-list">${result.admins.map(adminRow).join('')}</div></div></div>`;panel.querySelector('#approve-admin-form').addEventListener('submit',async event=>{event.preventDefault();const status=panel.querySelector('#admin-access-status');status.textContent='Saving…';try{await adminEdge('admins.upsert',{email:event.currentTarget.email.value});await renderAdminAccess(panel);}catch(e){status.textContent=e.message;}});panel.querySelectorAll('[data-admin-active]').forEach(btn=>btn.addEventListener('click',async()=>{await adminEdge('admins.set',{id:btn.dataset.adminActive,active:btn.dataset.activeNext==='true'});await renderAdminAccess(panel);}));}
function adminRow(a){if(a.role==='owner')return`<div class="admin-list-row"><div><strong>${escapeHtml(a.email)}</strong><span>Owner · Active</span></div><strong>Owner</strong></div>`;return`<div class="admin-list-row"><div><strong>${escapeHtml(a.email)}</strong><span>Admin · ${a.active?'Active':'Inactive'}</span></div><button data-admin-active="${a.id}" data-active-next="${!a.active}">${a.active?'Deactivate':'Reactivate'}</button></div>`;}

function bindAdminNav(){document.querySelectorAll('a[href="#admin"]').forEach(link=>link.addEventListener('click',()=>{if(adminState.approved&&!adminState.passwordChangeRequired){renderShell();setTimeout(()=>document.getElementById('admin-tools')?.scrollIntoView({behavior:'smooth',block:'start'}),80);}}));}
window.addEventListener('admin-state-changed',event=>{adminState=event.detail;if(adminState.approved&&!adminState.passwordChangeRequired)renderShell();});
window.addEventListener('veterans-products-updated',()=>import('./store.js').then(m=>m.loadProducts()).catch(console.error));
bindAdminNav();
if(adminState.approved&&!adminState.passwordChangeRequired)renderShell();
