import{getSupabaseClient}from'./supabase-client.js';
const client=getSupabaseClient();let adminState={user:null,approved:false,role:null,adminId:null};
export function normalizeEmail(value=''){return String(value).trim().toLowerCase();}
export function getAdminState(){return{...adminState};}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));}
export function renderAdminGate(state){if(!state.user)return`<div class="admin-gate-card"><h3>Owner & Admin Sign In</h3><p>Store and community management is restricted to approved Google accounts.</p><button class="gold-cta compact" type="button" data-google-signin>Sign in with Google</button></div>`;if(!state.approved)return`<div class="admin-gate-card"><h3>Access not approved</h3><p>This Google account is not approved for admin access.</p><button class="outline-button" type="button" data-admin-signout>Sign Out</button></div>`;return`<div class="admin-gate-card approved"><div><p class="eyebrow">Private Admin</p><h3>Admin Dashboard</h3><p>Signed in as ${escapeHtml(state.user.email||'')}</p></div><button class="outline-button" type="button" data-admin-signout>Sign Out</button></div><div id="admin-tools"></div>`;}
async function resolveAdminState(session){const user=session?.user||null;if(!user?.email)return{user,approved:false,role:null,adminId:null};const email=normalizeEmail(user.email);const{data,error}=await client.from('veterans_admins').select('id,email,role,active').eq('email',email).eq('active',true).maybeSingle();if(error)console.error('Admin permission check failed',error);return{user,approved:Boolean(data),role:data?.role||null,adminId:data?.id||null};}
function emitState(){window.dispatchEvent(new CustomEvent('admin-state-changed',{detail:getAdminState()}));}
async function refreshGate(sessionOverride){const session=sessionOverride??(await client.auth.getSession()).data.session;adminState=await resolveAdminState(session);const gate=document.getElementById('admin-gate');if(gate){gate.innerHTML=renderAdminGate(adminState);gate.querySelector('[data-google-signin]')?.addEventListener('click',signInWithGoogle);gate.querySelector('[data-admin-signout]')?.addEventListener('click',signOutAdmin);}emitState();}
export async function signInWithGoogle(){const redirectTo=`${location.origin}${location.pathname}#admin`;const{error}=await client.auth.signInWithOAuth({provider:'google',options:{redirectTo}});if(error)throw error;}
export async function signOutAdmin(){await client.auth.signOut();await refreshGate(null);}
client.auth.onAuthStateChange((_event,session)=>{queueMicrotask(()=>refreshGate(session));});refreshGate().catch(error=>{console.error(error);const gate=document.getElementById('admin-gate');if(gate)gate.innerHTML='<div class="status-error">Admin sign-in is temporarily unavailable.</div>';});
