import{getSupabaseClient}from'./supabase-client.js';
const client=getSupabaseClient();
const PRODUCTION_SITE_URL='https://haileybee.github.io/disabled-veterans-to-beekeepers/';
let adminState={user:null,approved:false,role:null,adminId:null};
export function normalizeEmail(value=''){return String(value).trim().toLowerCase();}
export function getAdminState(){return{...adminState};}
function escapeHtml(value){return String(value).replace(/[&<>'\"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[ch]));}
function redirectUrl(){return PRODUCTION_SITE_URL;}
function focusAdmin(){if(!adminState.approved)return;try{if(location.hash!=='#admin')history.replaceState(null,'',`${location.pathname}${location.search}#admin`);document.getElementById('admin')?.scrollIntoView({behavior:'smooth',block:'start'});}catch{}}
export function renderAdminGate(state){
  if(!state.user)return`<div class="admin-gate-card"><div><h3>Owner & Admin Sign In</h3><p>Sign in with an approved owner or admin email. After sign-in, tap <strong>Admin</strong> again to open your management tools.</p><form id="admin-email-form" class="admin-email-form"><label>Email<input name="email" type="email" autocomplete="email" required placeholder="approved@email.com"></label><button class="gold-cta compact" type="submit">Email Me a Sign-In Link</button><p id="admin-email-status" class="admin-form-status"></p></form><button class="outline-button" type="button" data-google-signin>Or sign in with Google</button></div></div>`;
  if(!state.approved)return`<div class="admin-gate-card"><h3>Access not approved</h3><p>${escapeHtml(state.user.email||'This account')} is signed in, but this email is not on the approved admin list.</p><button class="outline-button" type="button" data-admin-signout>Sign Out</button></div>`;
  return`<div class="admin-gate-card approved"><div><p class="eyebrow">Admin Unlocked</p><h3>Owner & Admin Dashboard</h3><p>Signed in as ${escapeHtml(state.user.email||'')}</p><p>Use the management tabs below for products, orders, Hive Stories, community moderation, and approved emails.</p></div><button class="outline-button" type="button" data-admin-signout>Sign Out</button></div><div id="admin-tools"></div>`;
}
async function resolveAdminState(session){const user=session?.user||null;if(!user?.email)return{user,approved:false,role:null,adminId:null};const email=normalizeEmail(user.email);const{data,error}=await client.from('veterans_admins').select('id,email,role,active').eq('email',email).eq('active',true).maybeSingle();if(error)console.error('Admin permission check failed',error);return{user,approved:Boolean(data),role:data?.role||null,adminId:data?.id||null};}
function emitState(){window.dispatchEvent(new CustomEvent('admin-state-changed',{detail:getAdminState()}));}
async function refreshGate(sessionOverride){const session=sessionOverride??(await client.auth.getSession()).data.session;adminState=await resolveAdminState(session);const gate=document.getElementById('admin-gate');if(gate){gate.innerHTML=renderAdminGate(adminState);gate.querySelector('[data-google-signin]')?.addEventListener('click',signInWithGoogle);gate.querySelector('[data-admin-signout]')?.addEventListener('click',signOutAdmin);gate.querySelector('#admin-email-form')?.addEventListener('submit',sendMagicLink);}emitState();if(adminState.approved&&location.hash==='#admin')setTimeout(focusAdmin,80);}
export async function signInWithGoogle(){const{error}=await client.auth.signInWithOAuth({provider:'google',options:{redirectTo:redirectUrl()}});if(error)throw error;}
async function sendMagicLink(event){event.preventDefault();const form=event.currentTarget;const status=form.querySelector('#admin-email-status');status.textContent='Sending secure sign-in link…';const email=normalizeEmail(form.email.value);try{const{error}=await client.auth.signInWithOtp({email,options:{emailRedirectTo:redirectUrl(),shouldCreateUser:true}});if(error)throw error;status.textContent='Check your email. The newest sign-in link will return you to this website.';}catch(error){status.textContent=error.message;}}
export async function signOutAdmin(){await client.auth.signOut();await refreshGate(null);}
client.auth.onAuthStateChange((event,session)=>{queueMicrotask(async()=>{await refreshGate(session);if(event==='SIGNED_IN'&&session){setTimeout(focusAdmin,120);}});});
refreshGate().catch(error=>{console.error(error);const gate=document.getElementById('admin-gate');if(gate)gate.innerHTML='<div class="status-error">Admin sign-in is temporarily unavailable.</div>';});
