import{edgeUrl,getSupabaseClient}from'./supabase-client.js';const client=getSupabaseClient();const GUEST_KEY='veteransChatGuestIdV1',NAME_KEY='veteransChatDisplayNameV1';let messages=[];
export function getGuestId(){let id=localStorage.getItem(GUEST_KEY);if(!id){id=crypto.randomUUID();localStorage.setItem(GUEST_KEY,id);}return id;}
function publicImageUrl(path){if(!path)return'';return client.storage.from('veterans-chat-images').getPublicUrl(path).data.publicUrl;}function escapeHtml(value){return String(value).replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));}
function renderMessages(){const list=document.getElementById('community-messages');if(!list)return;if(!messages.length){list.innerHTML='<div class="empty-state">Be the first to say hello to the community.</div>';return;}list.innerHTML=messages.map(m=>`<article class="chat-message" data-message-id="${m.id}"><div class="chat-meta"><strong>${escapeHtml(m.display_name)}</strong><time>${new Date(m.created_at).toLocaleString()}</time></div>${m.body?`<p>${escapeHtml(m.body)}</p>`:''}${m.image_path?`<img src="${publicImageUrl(m.image_path)}" alt="Photo shared by ${escapeHtml(m.display_name)}" loading="lazy">`:''}</article>`).join('');list.scrollTop=list.scrollHeight;}
async function loadMessages(){const{data,error}=await client.from('veterans_chat_messages').select('id,display_name,body,image_path,created_at').is('deleted_at',null).order('created_at',{ascending:true}).limit(100);if(error)throw error;messages=data||[];renderMessages();}
async function compressImage(file){if(!file)return null;if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Please choose a JPG, PNG, or WebP photo.');if(file.size>8*1024*1024)throw new Error('That photo is too large. Please choose one under 8 MB.');const bitmap=await createImageBitmap(file);const max=1600,scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.82));if(!blob||blob.size>2*1024*1024)throw new Error('The compressed photo is still too large. Try a smaller image.');return await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(blob);});}
async function sendMessage(event){event.preventDefault();const form=event.currentTarget,status=document.getElementById('community-status'),displayName=form.displayName.value.trim(),body=form.message.value.trim(),file=form.photo.files[0]||null;if(!displayName){status.textContent='Please enter your display name.';return;}if(!body&&!file){status.textContent='Write a message or add a photo.';return;}localStorage.setItem(NAME_KEY,displayName);const submit=form.querySelector('button[type="submit"]');submit.disabled=true;status.textContent='Posting…';try{const imageDataUrl=await compressImage(file);const response=await fetch(edgeUrl('veterans-chat-post'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({guestId:getGuestId(),displayName,body,imageDataUrl})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||'Message could not be posted.');form.message.value='';form.photo.value='';status.textContent='Posted.';if(payload.message&&!messages.some(m=>m.id===payload.message.id)){messages.push(payload.message);renderMessages();}}catch(error){status.textContent=error.message;}finally{submit.disabled=false;}}
function initForm(){const form=document.getElementById('community-form');if(!form)return;form.displayName.value=localStorage.getItem(NAME_KEY)||'';form.addEventListener('submit',sendMessage);}function subscribe(){client.channel('veterans-community-public').on('postgres_changes',{event:'INSERT',schema:'public',table:'veterans_chat_messages'},payload=>{if(payload.new.deleted_at||messages.some(m=>m.id===payload.new.id))return;messages.push(payload.new);if(messages.length>100)messages.shift();renderMessages();}).on('postgres_changes',{event:'UPDATE',schema:'public',table:'veterans_chat_messages'},payload=>{if(payload.new.deleted_at)messages=messages.filter(m=>m.id!==payload.new.id);else messages=messages.map(m=>m.id===payload.new.id?payload.new:m);renderMessages();}).subscribe();}
initForm();loadMessages().catch(error=>{console.error(error);const host=document.getElementById('community-messages');if(host)host.innerHTML='<div class="status-error">Community chat could not load.</div>';});subscribe();
