import{getSupabaseClient}from'./supabase-client.js';
import{getAdminState}from'./auth.js?v=52';

const client=getSupabaseClient();
let adminState=getAdminState();
let editingStoryId=null;
let storyRows=[];

function escapeHtml(value=''){return String(value).replace(/[&<>'\"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[ch]));}
function publicImage(path){if(!path)return'';return client.storage.from('veterans-hive-story-images').getPublicUrl(path).data.publicUrl||'';}
function formatDate(value){if(!value)return'No story date';const date=new Date(`${value}T12:00:00`);return Number.isNaN(date.getTime())?value:date.toLocaleDateString();}

async function uploadPhoto(file,storyId){if(!file)return null;if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Story photo must be JPG, PNG, or WebP.');if(file.size>5*1024*1024)throw new Error('Story photo must be 5 MB or smaller.');const ext=file.type==='image/png'?'png':file.type==='image/webp'?'webp':'jpg';const path=`${storyId}/${crypto.randomUUID()}.${ext}`;const{error}=await client.storage.from('veterans-hive-story-images').upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;return path;}

async function removePhoto(path){if(!path)return;const{error}=await client.storage.from('veterans-hive-story-images').remove([path]);if(error)console.warn('Could not remove old Hive Story image',error);}

function storyListRow(story){const image=publicImage(story.image_path);return`<div class="admin-list-row hive-row"><div>${image?`<img class="hive-story-admin-thumb" src="${escapeHtml(image)}" alt="">`:''}<div><strong>${escapeHtml(story.title)}</strong><span>${escapeHtml(story.hive_name||'Hive Story')} · ${escapeHtml(formatDate(story.story_date))} · ${story.published?'Published':'Draft'}</span></div></div><div class="row-actions"><button type="button" data-edit-hive-story="${story.id}">Edit</button><button type="button" data-delete-hive-story="${story.id}">Delete</button></div></div>`;}

async function loadAdminStories(){const host=document.getElementById('hive-admin-tools');if(!host||!adminState.approved)return;host.innerHTML='<p class="admin-loading">Loading Hive Stories manager…</p>';const{data,error}=await client.from('veterans_hive_stories').select('*').order('created_at',{ascending:false});if(error){host.innerHTML=`<div class="status-error">${escapeHtml(error.message)}</div>`;return;}storyRows=data||[];renderManager(host);}

function renderManager(host){const editing=editingStoryId?storyRows.find(s=>s.id===editingStoryId):null;host.innerHTML=`<div class="hive-admin-heading"><p class="eyebrow">Site Owner Tools</p><h3>${editing?'Edit Hive Story':'Add a Hive Story'}</h3><p>Publish stories about hives you have helped, including a photo, location, date, and the full story.</p></div><div class="admin-grid-two"><form id="hive-story-form" class="admin-card"><h3>${editing?'Edit Story':'New Hive Story'}</h3><label>Story Title<input name="title" maxlength="140" required placeholder="A New Hive, A New Beginning"></label><div class="form-row"><label>Hive Name<input name="hiveName" maxlength="120" placeholder="Optional"></label><label>Location<input name="location" maxlength="160" placeholder="City, Michigan"></label></div><label>Story Date<input name="storyDate" type="date"></label><label>Short Summary<textarea name="excerpt" rows="3" maxlength="320" placeholder="A short introduction shown on the story card."></textarea></label><label>Full Story<textarea name="body" rows="9" maxlength="12000" required placeholder="Tell the story of the hive, who was helped, what happened, and how the hive is doing."></textarea></label><label>Story Photo<input name="photo" type="file" accept="image/jpeg,image/png,image/webp"></label><label class="check-row"><input name="published" type="checkbox" checked> Publish on the website</label><div class="form-actions"><button class="gold-cta compact" type="submit">${editing?'Save Changes':'Publish Story'}</button><button class="outline-button" type="button" data-clear-hive-story>${editing?'Cancel Edit':'Clear'}</button></div><p class="admin-form-status" id="hive-story-status"></p></form><div class="admin-card"><h3>Hive Stories</h3><div class="admin-list">${storyRows.map(storyListRow).join('')||'<p>No Hive Stories yet. Add the first one using the form.</p>'}</div></div></div>`;
const form=host.querySelector('#hive-story-form');if(editing){form.title.value=editing.title||'';form.hiveName.value=editing.hive_name||'';form.location.value=editing.location||'';form.storyDate.value=editing.story_date||'';form.excerpt.value=editing.excerpt||'';form.body.value=editing.body||'';form.published.checked=Boolean(editing.published);}form.addEventListener('submit',saveStory);host.querySelector('[data-clear-hive-story]').addEventListener('click',()=>{editingStoryId=null;renderManager(host);});host.querySelectorAll('[data-edit-hive-story]').forEach(btn=>btn.addEventListener('click',()=>{editingStoryId=btn.dataset.editHiveStory;renderManager(host);host.scrollIntoView({behavior:'smooth',block:'start'});}));host.querySelectorAll('[data-delete-hive-story]').forEach(btn=>btn.addEventListener('click',()=>deleteStory(btn.dataset.deleteHiveStory)));}

async function saveStory(event){event.preventDefault();const form=event.currentTarget;const status=form.querySelector('#hive-story-status');status.textContent='Saving Hive Story…';try{const existing=editingStoryId?storyRows.find(s=>s.id===editingStoryId):null;const storyId=editingStoryId||crypto.randomUUID();let imagePath=existing?.image_path||null;if(form.photo.files[0]){const newPath=await uploadPhoto(form.photo.files[0],storyId);if(existing?.image_path&&newPath!==existing.image_path)await removePhoto(existing.image_path);imagePath=newPath;}const payload={id:storyId,title:form.title.value.trim(),hive_name:form.hiveName.value.trim(),location:form.location.value.trim(),story_date:form.storyDate.value||null,excerpt:form.excerpt.value.trim(),body:form.body.value.trim(),image_path:imagePath,published:form.published.checked,updated_at:new Date().toISOString()};const query=editingStoryId?client.from('veterans_hive_stories').update(payload).eq('id',storyId):client.from('veterans_hive_stories').insert(payload);const{error}=await query;if(error)throw error;editingStoryId=null;await loadAdminStories();window.dispatchEvent(new CustomEvent('veterans-hive-stories-updated'));}catch(error){status.textContent=error.message;}}

async function deleteStory(id){const story=storyRows.find(s=>s.id===id);if(!story||!confirm(`Delete “${story.title}”?`))return;const{error}=await client.from('veterans_hive_stories').delete().eq('id',id);if(error){alert(error.message);return;}await removePhoto(story.image_path);if(editingStoryId===id)editingStoryId=null;await loadAdminStories();window.dispatchEvent(new CustomEvent('veterans-hive-stories-updated'));}

function syncState(state){adminState=state;const host=document.getElementById('hive-admin-tools');if(!host)return;if(adminState.approved)loadAdminStories();else host.innerHTML='';}
export async function openHiveAdmin(){adminState=getAdminState();if(adminState.approved)await loadAdminStories();}
window.addEventListener('admin-state-changed',event=>syncState(event.detail));
