import{getSupabaseClient}from'./supabase-client.js';const client=getSupabaseClient();const CART_KEY='veteransStoreCartV1';let products=[];let cart=readCart();
export function formatMoney(minor,currency='USD'){return new Intl.NumberFormat('en-US',{style:'currency',currency}).format(Number(minor||0)/100);}
export function readCart(){try{const parsed=JSON.parse(localStorage.getItem(CART_KEY)||'[]');return Array.isArray(parsed)?parsed.filter(x=>x?.productId&&Number.isInteger(x.quantity)&&x.quantity>0):[];}catch{return[];}}
function saveCart(){localStorage.setItem(CART_KEY,JSON.stringify(cart));window.dispatchEvent(new CustomEvent('veterans-cart-changed',{detail:getCartForCheckout()}));renderCart();}
export function getCartForCheckout(){return cart.map(({productId,quantity})=>({productId,quantity}));}export function clearCart(){cart=[];saveCart();}
function addToCart(productId){const product=products.find(p=>p.id===productId);if(!product||!product.active||product.stock_quantity<1)return;const line=cart.find(x=>x.productId===productId);if(line)line.quantity=Math.min(line.quantity+1,product.stock_quantity,99);else cart.push({productId,quantity:1});saveCart();}
function setQuantity(productId,value){const product=products.find(p=>p.id===productId);if(!product)return;const quantity=Math.max(0,Math.min(Number(value)||0,product.stock_quantity,99));if(quantity===0)cart=cart.filter(x=>x.productId!==productId);else{const line=cart.find(x=>x.productId===productId);if(line)line.quantity=quantity;}saveCart();}
function productImageUrl(path){if(!path)return'';return client.storage.from('veterans-product-images').getPublicUrl(path).data.publicUrl;}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));}
function renderProducts(){const grid=document.getElementById('store-products');if(!grid)return;if(!products.length){grid.innerHTML='<div class="empty-state">Products are being prepared. Check back soon.</div>';return;}grid.innerHTML=products.map(p=>{const soldOut=!p.active||p.stock_quantity<1;const image=productImageUrl(p.image_path);return`<article class="product-card"><div class="product-photo">${image?`<img src="${image}" alt="${escapeHtml(p.name)}">`:'<div class="product-placeholder">Veteran Beekeepers</div>'}</div><div class="product-copy"><h3>${escapeHtml(p.name)}</h3><p>${escapeHtml(p.description||'')}</p><div class="product-buy"><strong>${formatMoney(p.price_minor_units,p.currency)}</strong><button class="gold-cta compact" data-add-product="${p.id}" ${soldOut?'disabled':''}>${soldOut?'Sold Out':'Add to Cart'}</button></div></div></article>`;}).join('');grid.querySelectorAll('[data-add-product]').forEach(btn=>btn.addEventListener('click',()=>addToCart(btn.dataset.addProduct)));}
function renderCart(){const box=document.getElementById('store-cart');const count=document.getElementById('cart-count');if(count)count.textContent=String(cart.reduce((n,x)=>n+x.quantity,0));if(!box)return;const lines=cart.map(line=>({...line,product:products.find(p=>p.id===line.productId)})).filter(x=>x.product);if(!lines.length){box.innerHTML='<p class="empty-state">Your cart is empty.</p><div id="paypal-checkout"></div>';window.dispatchEvent(new CustomEvent('veterans-cart-rendered'));return;}const total=lines.reduce((sum,line)=>sum+line.product.price_minor_units*line.quantity,0);box.innerHTML=`<div class="cart-lines">${lines.map(line=>`<div class="cart-line"><div><strong>${escapeHtml(line.product.name)}</strong><span>${formatMoney(line.product.price_minor_units,line.product.currency)} each</span></div><label>Qty <input type="number" min="0" max="${line.product.stock_quantity}" value="${line.quantity}" data-cart-qty="${line.productId}"></label></div>`).join('')}</div><div class="cart-total"><span>Estimated total</span><strong>${formatMoney(total)}</strong></div><p class="fine-print">Final price and stock are verified securely before PayPal opens.</p><div id="paypal-checkout"></div>`;box.querySelectorAll('[data-cart-qty]').forEach(input=>input.addEventListener('change',()=>setQuantity(input.dataset.cartQty,input.value)));window.dispatchEvent(new CustomEvent('veterans-cart-rendered'));}
export async function loadProducts(){const{data,error}=await client.from('veterans_products').select('*').eq('active',true).order('created_at',{ascending:false});if(error)throw error;products=data||[];cart=cart.filter(line=>products.some(p=>p.id===line.productId));renderProducts();renderCart();}
loadProducts().catch(error=>{console.error(error);const grid=document.getElementById('store-products');if(grid)grid.innerHTML='<div class="status-error">The store could not load right now.</div>';});
